#####################################################################
# Lab01 secret-free eNB teaching profile
# Profile: lab01-student-zmq-lte
#####################################################################

[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
s1c_bind_port = 0
n_prb = 50

[enb_files]
sib_config = sib.conf
rr_config = rr.conf
rb_config = rb.conf

[rf]
device_name = zmq
device_args = fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://10.0.0.2:2001,id=enb,base_srate=23.04e6

[pcap]
enable = false
s1ap_enable = false

[log]
all_level = info
all_hex_limit = 32
filename = stdout

[gui]
enable = false

[scheduler]
pusch_max_mcs = 16
min_nof_ctrl_symbols = 1
max_nof_ctrl_symbols = 3

[embms]
enable = false
